In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Forest Types Dataset.csv")
df.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,1,2596,51,3,258,0,510,221,232,148,...,0,0,0,0,0,0,0,0,0,5
1,2,2590,56,2,212,-6,390,220,235,151,...,0,0,0,0,0,0,0,0,0,5
2,3,2804,139,9,268,65,3180,234,238,135,...,0,0,0,0,0,0,0,0,0,2
3,4,2785,155,18,242,118,3090,238,238,122,...,0,0,0,0,0,0,0,0,0,2
4,5,2595,45,2,153,-1,391,220,234,150,...,0,0,0,0,0,0,0,0,0,5


In [3]:
#To check the datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15119 entries, 0 to 15118
Data columns (total 56 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Id                                  15119 non-null  int64
 1   Elevation                           15119 non-null  int64
 2   Aspect                              15119 non-null  int64
 3   Slope                               15119 non-null  int64
 4   Horizontal_Distance_To_Hydrology    15119 non-null  int64
 5   Vertical_Distance_To_Hydrology      15119 non-null  int64
 6   Horizontal_Distance_To_Roadways     15119 non-null  int64
 7   Hillshade_9am                       15119 non-null  int64
 8   Hillshade_Noon                      15119 non-null  int64
 9   Hillshade_3pm                       15119 non-null  int64
 10  Horizontal_Distance_To_Fire_Points  15119 non-null  int64
 11  Wilderness_Area1                    15119 non-null  int64
 12  Wild

In [4]:
#To check the size
df.shape

(15119, 56)

In [6]:
#To check the null value
df.isnull().sum()

Id                                    0
Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0


In [7]:
# 'Cover_Type' is our output value
df['Cover_Type'].value_counts()

5    2160
2    2160
1    2160
7    2160
6    2160
4    2160
3    2159
Name: Cover_Type, dtype: int64

In [8]:
#X and Y axis
X = df.drop('Cover_Type', axis=1)
y = df['Cover_Type']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
X_train.shape

(12095, 55)

In [12]:
X_test.shape

(3024, 55)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
lg = LogisticRegression()

In [15]:
lg.fit(X_train,y_train)
y_pred = lg.predict(X_test)
y_pred

C:\Users\CSC\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([4, 2, 7, ..., 4, 3, 4], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(y_test,y_pred)

0.37367724867724866

In [18]:
#The accuarcy is not good. lets try with Decision Tree algo

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
dtc = DecisionTreeClassifier()

In [21]:
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
accuracy_score(y_test,y_pred)

0.8141534391534392

In [23]:
#Lets check with RandomForest classifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [24]:
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
accuracy_score(y_test,y_pred)

0.8842592592592593

In [25]:
df['Cover_Type'].value_counts()

5    2160
2    2160
1    2160
7    2160
6    2160
4    2160
3    2159
Name: Cover_Type, dtype: int64

In [26]:
#To we have 7 class output=> multi class classification

# Prediction

In [28]:
df.iloc[10].values

array([  11, 2612,  201,    4,  180,   51,  735,  218,  243,  161, 6222,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          5], dtype=int64)

In [29]:
user_input = ( 11, 2612,  201,    4,  180,   51,  735,  218,  243,  161, 6222,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0)
np_arr = np.asarray(user_input)
reshaped_arr = np_arr.reshape(1,-1)
prediction = rfc.predict(reshaped_arr)
prediction

C:\Users\CSC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([5], dtype=int64)

# Save Model

In [30]:
import pickle
pickle.dump(rfc,open('rfc.pkl','wb'))